services:
  db:
    image: postgres:15-alpine
    container_name: sacolas-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: sacolas
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: